# Generated by Django 5.1.1 on 2024-10-23 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0003_rename_profile_image_url_profile_pfp_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.ImageField(upload_to="images/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mini_fb.statusmessage",
                    ),
                ),
            ],
        ),
    ]
